# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hrema <hrema@student.21-school.ru>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/04 19:05:28 by hrema             #+#    #+#              #
#    Updated: 2020/12/04 19:05:29 by hrema            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: minikube
      protocol: layer2
      addresses:
      - 192.168.99.201-192.168.99.201