# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hrema <hrema@student.21-school.ru>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/07 14:21:49 by hrema             #+#    #+#              #
#    Updated: 2020/12/07 14:22:03 by hrema            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.201
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050
