# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    telegraf.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hrema <hrema@student.21-school.ru>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/07 14:21:02 by hrema             #+#    #+#              #
#    Updated: 2020/12/07 14:21:03 by hrema            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
      app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 5
  template:
    metadata:
      name: telegraf
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf
          imagePullPolicy: Never
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket